const countryMap = {
    'FI': 'Finland',
    'US': 'United States',
    'GB': 'United Kingdom',
    'FR': 'France',
    'DE': 'Germany',
    'IT': 'Italy',
    'ES': 'Spain',
    'SE': 'Sweden',
    'RU': 'Russia',
    'JP': 'Japan',
    'IN': 'India',
    'CA': 'Canada',
    'BR': 'Brazil',
    'MX': 'Mexico',
    'AU': 'Australia',
    'CN': 'China',
    'KR': 'South Korea',
    'HK': 'Hong Kong',
    'TW': 'Taiwan',
    'SG': 'Singapore',
    'ZA': 'South Africa',
    'NL': 'Netherlands',
    'BE': 'Belgium',
    'DK': 'Denmark',
    'NO': 'Norway',
    'IE': 'Ireland',
    'PT': 'Portugal',
    'CH': 'Switzerland',
    'AT': 'Austria',
    'GR': 'Greece',
    'PL': 'Poland',
    'CZ': 'Czech Republic',
    'HU': 'Hungary',
    'TR': 'Turkey',
    'AR': 'Argentina',
    'CL': 'Chile',
    'CO': 'Colombia',
    'PE': 'Peru',
    'VE': 'Venezuela',
    'PH': 'Philippines',
    'ID': 'Indonesia',
    'MY': 'Malaysia',
    'TH': 'Thailand',
    'VN': 'Vietnam',
    // Add more countries as needed
  }

  export default countryMap