// Mapping of language codes to language names
const languageMap = {
    'fi': 'Finnish',
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'de': 'German',
    'sv': 'Swedish',
    'it': 'Italian',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'zh': 'Chinese',
    'ja': 'Japanese',
    'ko': 'Korean',
    'ar': 'Arabic',
    'hi': 'Hindi',
    'bn': 'Bengali',
    'pl': 'Polish',
    'tr': 'Turkish',
    'nl': 'Dutch',
    'da': 'Danish',
    'no': 'Norwegian',
    'cs': 'Czech',
    'hu': 'Hungarian',
    'ro': 'Romanian',
    'th': 'Thai',
    'vi': 'Vietnamese',
    'uk': 'Ukrainian',
    'he': 'Hebrew',
    'el': 'Greek',
    'id': 'Indonesian',
    'ms': 'Malay',
    'ta': 'Tamil',
    'te': 'Telugu',
    'ml': 'Malayalam',
    'mr': 'Marathi',
    'gu': 'Gujarati',
    'kn': 'Kannada',
    'pa': 'Punjabi',
    'si': 'Sinhala',
    'ur': 'Urdu',
    'sw': 'Swahili',
    'fil': 'Filipino',
    'ca': 'Catalan',
    'eu': 'Basque',
    'hr': 'Croatian',
    'sr': 'Serbian',
    'bs': 'Bosnian',
    'mk': 'Macedonian',
    'sq': 'Albanian',
    'lv': 'Latvian',
    'lt': 'Lithuanian',
    'et': 'Estonian',
    'is': 'Icelandic',
    'gl': 'Galician',
    'cy': 'Welsh',
    'tl': 'Tagalog',
    'se': 'Northern Sami',
    'ga': 'Irish',

    // Add more language codes and their full names as needed
}

export default languageMap